import { z } from 'zod';

export const RequestIdSchema = z
  .string()
  .min(1)
  .max(128)
  .regex(/^[A-Za-z0-9_-]+$/)
  .describe('Opaque server-generated request identifier.');

export const ServerTimestampSchema = z.iso
  .datetime()
  .describe('UTC ISO 8601 timestamp generated by the API server.');

export const ResponseMetadataSchema = z
  .strictObject({
    requestId: RequestIdSchema,
    timestamp: ServerTimestampSchema,
  })
  .describe('Safe metadata returned by a public API response.');

export type RequestId = z.infer<typeof RequestIdSchema>;
export type ServerTimestamp = z.infer<typeof ServerTimestampSchema>;
export type ResponseMetadata = z.infer<typeof ResponseMetadataSchema>;
