/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 earth.gltf 
Author: cmzw (https://sketchfab.com/cmzw)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-planet-789725db86f547fc9163b00f302c3e70
Title: Stylized planet
*/

import { useAnimations, useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { useRef } from 'react';

export default function Model(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF('/earth/earth.gltf');
	const { actions } = useAnimations(animations, group);

	const cloudRef = useRef(null);
	const planetRef = useRef(null);

	useFrame(() => {
		if (!planetRef.current || !cloudRef.current) {
			return;
		}
		planetRef.current.rotation.y -= 0.005;
		cloudRef.current.rotation.y -= 0.001;
	});

	return (
		<group
			ref={group}
			{...props}
			dispose={null}>
			<group name="Sketchfab_Scene">
				<group
					name="Sketchfab_model"
					rotation={[-1.54, -0.064, 0]}>
					<group name="root">
						<group
							name="GLTF_SceneRootNode"
							rotation={[Math.PI / 2, 0, 0]}>
							<group name="Clouds_1">
								<mesh
									ref={cloudRef}
									name="Object_4"
									geometry={nodes.Object_4.geometry}
									material={materials.Clouds}
								/>
							</group>
							<group name="Planet_2">
								<mesh
									ref={planetRef}
									name="Object_6"
									geometry={nodes.Object_6.geometry}
									material={materials.Planet}
								/>
							</group>
						</group>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload('/earth/earth.gltf');
